[package]
name = "rustes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitflags = { version = "2.4.0", features = [] }

sdl2 = "0.35.2"
rand = "0.8.5"


